authentication/urls.py
from django.urls import path
from authentication.views import register, login_user, logout_user

app_name = 'authentication'

urlpatterns = [
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
]

bodynsoul/urls.py
from django.urls import path, include

urlpatterns = [
    path("admin/", include("admin.urls", namespace="admin")),
    path("", include("main.urls")),
    path("", include("authentication.urls", namespace="authentication")),
    path("", include("calorie_tracking.urls", namespace="calorie_tracking")),
    path("", include("list_information.urls", namespace="list_information")),
    path("", include("problem_report.urls", namespace="problem_report")),
    path("", include("mood_tracking.urls", namespace="mood_tracking")),
]

calorie_tracking/urls.py
from django.urls import path
from calorie_tracking.views import calorie_tracking, add_to_tracking, stats, delete_item

app_name = "calorie_tracking"

urlpatterns = [
    path('calorie_tracking/', calorie_tracking, name='calorie_tracking'),
    path('add_to_tracking/', add_to_tracking, name='add_to_tracking'),
    path('stats/', stats, name='stats'),
    path('delete_item/<int:item_id>/', delete_item, name='delete_item'),
    ]

list_information/urls.py
from django.urls import path
from list_information.views import data_information, data_list

app_name = "list_information"

urlpatterns = [
    path('nutritional-information', data_information, name='data_information'),
    path('', data_list, name='data_list')
]

main/urls.py
from django.urls import path
from main.views import report_list

app_name = 'main'

urlpatterns = [
    path('report-list', report_list, name='report_list'),
]

urlpatterns = [
    path('admin/', admin.site.urls),
    path('mood_tracking/', include('mood_tracking.urls')),
    # Include other app URLs here as needed
]

problem_report/urls.py
from django.urls import path
from problem_report.views import problem_report

app_name = 'problem_report'

urlpatterns = [
    path('problem-report', problem_report, name='problem_report'),
]

calorie_tracking/views.py
from django.shortcuts import redirect, get_object_or_404
from django.shortcuts import render
from main.models import Data, Stats
from django.http import HttpResponseNotAllowed, JsonResponse
from main.forms import CalorieTrackingForm, StatsForm
from main.models import CalorieTracking

def calorie_tracking(request):
    tracking_items = CalorieTracking.objects.filter(user=request.user)
    
    try:
        user_stats = Stats.objects.get(user=request.user)
        recommended_calories = calculate_recommended_calories(
            user_stats.weight, user_stats.height, user_stats.age, user_stats.activity_level
        )
    except Stats.DoesNotExist:
        user_stats = None
        recommended_calories = None
    
    if request.method == 'POST':
        form = CalorieTrackingForm(request.POST)
        if form.is_valid():
            item_id = form.cleaned_data['item'].id  # Access the item id correctly
            item = Data.objects.get(pk=item_id)
            
            CalorieTracking.objects.create(user=request.user, item=item)
            
            return redirect('list_information:data_information')
    else:
        form = CalorieTrackingForm()
    
    return render(request, 'calorie_tracking.html', {'form': form, 'tracking_items': tracking_items, 'user_stats': user_stats, 'recommended_calories': recommended_calories})


def add_to_tracking(request):
    if request.method == 'POST':
        item_id = request.POST.get('item_id')
        item = get_object_or_404(Data, pk=item_id)
        CalorieTracking.objects.create(user=request.user, item=item)
        return JsonResponse({'status': 'success'})
    else:
        return HttpResponseNotAllowed(['POST'])


def stats(request):
    if request.method == 'POST':
        form = StatsForm(request.POST, user=request.user)
        if form.is_valid():
            Stats.objects.create(
                user=request.user,
                weight=form.cleaned_data['weight'],
                height=form.cleaned_data['height'],
                age=form.cleaned_data['age'],
                activity_level=form.cleaned_data['activity_level']
            )
            return redirect('calorie_tracking:calorie_tracking')
    else:
        form = StatsForm(user=request.user)
    return render(request, 'stats.html', {'form': form})

def delete_item(request, item_id):
    item = get_object_or_404(CalorieTracking, pk=item_id)
    item.delete()
    return redirect('calorie_tracking:calorie_tracking')

def calculate_recommended_calories(weight, height, age, activity_level):
    bmr = 88.362 + (13.397 * weight) + (4.799 * height) - (5.677 * age)
    
    activity_factors = {
        'sedentary': 1.2,
        'lightly_active': 1.375,
        'moderately_active': 1.55,
        'very_active': 1.725,
        'extra_active': 1.9
    }
    
    tdee = bmr * activity_factors.get(activity_level, 1.2)
    return round(tdee)

calorie_tracking/templates/calorie_tracking.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <title>Calorie Tracking</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>

<body>
  <div class="container mt-5">
    <h1>Food is not your enemy!</h1>
    <div class="d-flex justify-content-between mb-3">
      <a href="{% url 'list_information:data_information' %}" class="btn btn-primary">
        Back
      </a>
      <a href="{% url 'problem_report:problem_report' %}" class="btn btn-primary">
        Problem Report
      </a>
      <a href="{% url 'authentication:logout' %}" class="btn btn-danger">
        Logout
      </a>
    </div>

    {% if user_stats %}
      <div class="card mb-3">
        <div class="card-header">
          Your Stats
        </div>
        <div class="card-body">
          <p>Weight: {{ user_stats.weight }} kg</p>
          <p>Height: {{ user_stats.height }} cm</p>
          <p>Age: {{ user_stats.age }} years</p>
          <p>Recommended Daily Calorie Intake: <span id="recommended-calories">{{ recommended_calories }}</span> kcal</p>
        </div>
      </div>
    {% else %}
      <div class="alert alert-warning" role="alert">
        You have not provided your stats yet.
      </div>
    {% endif %}

    <table class="table table-striped">
      <thead>
        <tr>
          <th>Category</th>
          <th>Description</th>
          <th>Kilocalories</th>
          <th>Protein</th>
          <th>Fat</th>
          <th>Carbohydrate</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        {% for tracking_item in tracking_items %}
        <tr>
          <td>{{ tracking_item.item.category }}</td>
          <td>{{ tracking_item.item.description }}</td>
          <td class="item-calories">{{ tracking_item.item.kilocalories }}</td>
          <td>{{ tracking_item.item.protein }}</td>
          <td>{{ tracking_item.item.fat }}</td>
          <td>{{ tracking_item.item.carbohydrate }}</td>
          <td>
            <a href="{% url 'calorie_tracking:delete_item' tracking_item.id %}" class="btn btn-danger">Delete</a>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>

    <div id="total-calories" class="mt-3"></div>

  </div>

  <!-- Bootstrap JS and jQuery -->
  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

  <script>
    document.addEventListener("DOMContentLoaded", function() {
      const recommendedCalories = parseInt(document.getElementById("recommended-calories").textContent);
      let totalCalories = 0;

      document.querySelectorAll(".item-calories").forEach(function(item) {
        totalCalories += parseInt(item.textContent);
      });

      const totalCaloriesDiv = document.getElementById("total-calories");
      totalCaloriesDiv.innerHTML = `Total Calories: ${totalCalories} kcal`;

      if (totalCalories > recommendedCalories) {
        totalCaloriesDiv.style.color = "red";
      } else {
        totalCaloriesDiv.style.color = "green";
      }
    });
  </script>

</body>

</html>

calorie_tracking/templates/stats.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <title>Stats</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>

<body>
  <div class="container mt-5">
    <h1>Tell us about you</h1>
    <a href="{% url 'problem_report:problem_report' %}">
      <button class="btn btn-primary">
        Problem Report
      </button>
    </a>
    <a href="{% url 'authentication:logout' %}">
      <button class="btn btn-primary">
        Logout
      </button>
    </a>

    <form method="POST">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit" class="btn btn-primary">Submit</button>
    </form>

</body>

</html>